# Generated by Django 6.0.1 on 2026-01-26 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Nº Protocolo')),
                ('tipo', models.CharField(choices=[('CORRETIVA', 'Manutenção Corretiva (Quebra/Erro)'), ('PREVENTIVA', 'Manutenção Preventiva'), ('REQUISICAO', 'Requisição de Serviço (Config/Instalação)'), ('DUVIDA', 'Dúvida / Suporte')], default='REQUISICAO', max_length=20)),
                ('titulo', models.CharField(max_length=100, verbose_name='Assunto')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema/Solicitação')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica - Parada de Produção')], default='MEDIA', max_length=10)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_PECA', 'Aguardando Peças/Terceiros'), ('RESOLVIDO', 'Resolvido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('relatorio_tecnico', models.TextField(blank=True, help_text='Descreva o que foi feito.', verbose_name='Laudo/Solução')),
                ('historico_transferencias', models.TextField(blank=True, default='', editable=False, help_text='Registro automático de trocas de técnicos.', verbose_name='Log de Transferências')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.categoriaservico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.empresa')),
                ('equipamento', models.ForeignKey(blank=True, help_text='Selecione se o chamado for referente a um equipamento específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_chamados', to='equipment.equipamento')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.setor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
                ('tecnico_atribuido', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_tecnicos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Chamado / O.S.',
                'verbose_name_plural': 'Chamados e O.S.',
                'ordering': ['-aberto_em'],
            },
        ),
    ]
