# Generated by Django 6.0.1 on 2026-03-04 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('destinatarios', models.TextField(blank=True, help_text='Lista de e-mails que receberão a notificação.', verbose_name='Destinatários')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Na Fila)'), ('ENVIADO', 'Enviado com Sucesso'), ('ERRO', 'Erro no Envio')], default='PENDENTE', max_length=20, verbose_name='Status de Envio')),
                ('erro_mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_email', to='orders.chamado')),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mails',
                'ordering': ['-criado_em'],
            },
        ),
    ]
