# Generated by Django 6.0.1 on 2026-03-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresas_atendidas',
            field=models.ManyToManyField(blank=True, help_text='Selecione quais empresas este técnico pode visualizar e atender.', related_name='tecnicos_atribuidos', to='companies.empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_tecnico',
            field=models.BooleanField(default=False, help_text='Designa se este utilizador é um técnico de atendimento.', verbose_name='É Técnico?'),
        ),
    ]
