# Generated by Django 6.0.1 on 2026-01-26 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Notebook do João', max_length=100, verbose_name='Nome/Identificação')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='companies.empresa')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Quem está utilizando o equipamento atualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.setor')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos (Geral)',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.equipamento')),
                ('processador', models.CharField(help_text='Ex: Intel Core i7 12ª Ger', max_length=100)),
                ('memoria_ram', models.CharField(help_text='Ex: 16GB DDR4', max_length=50, verbose_name='Memória RAM')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
            bases=('equipment.equipamento',),
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HDD', 'Disco Rígido (HDD)'), ('SSD', 'SSD SATA'), ('NVME', 'SSD NVMe/M.2')], default='SSD', max_length=10)),
                ('tamanho', models.CharField(help_text='Ex: 512GB, 1TB', max_length=50)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discos', to='equipment.computador')),
            ],
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('equipamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.equipamento')),
                ('tipo', models.CharField(choices=[('MONITOR', 'Monitor'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('HEADSET', 'Headset'), ('IMPRESSORA', 'Impressora'), ('OUTRO', 'Outro')], max_length=20)),
                ('conectado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos_conectados', to='equipment.computador', verbose_name='Conectado ao Computador')),
            ],
            options={
                'verbose_name': 'Periférico',
                'verbose_name_plural': 'Periféricos',
            },
            bases=('equipment.equipamento',),
        ),
    ]
