# Generated by Django 6.0.1 on 2026-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sistema', models.CharField(default='TI Manager', help_text='Texto que aparece na barra superior (Navbar).', max_length=100, verbose_name='Título do Sistema (Header)')),
                ('texto_rodape', models.CharField(default='Sistema de Gestão de TI. Todos os direitos reservados.', help_text='Texto de copyright que aparece no final da página.', max_length=255, verbose_name='Texto do Rodapé')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
    ]
