# Generated by Django 6.0.1 on 2026-02-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_smtp', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Servidor SMTP (Host)')),
                ('porta', models.IntegerField(default=587, verbose_name='Porta')),
                ('usuario', models.CharField(blank=True, help_text='Ex: seu-email@gmail.com', max_length=255, null=True, verbose_name='Usuário (E-mail)')),
                ('senha', models.CharField(blank=True, help_text='Senha do e-mail ou senha de aplicativo (App Password)', max_length=255, null=True, verbose_name='Senha / App Password')),
                ('usar_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('usar_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_remetente', models.EmailField(default='nao-responda@meusistema.com', help_text='O e-mail que aparecerá como remetente para os utilizadores.', max_length=254, verbose_name='E-mail do Remetente (De)')),
            ],
            options={
                'verbose_name': 'Servidor de E-mail',
                'verbose_name_plural': 'Servidor de E-mail',
            },
        ),
    ]
