# Generated by Django 6.0.1 on 2026-02-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaoemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='site_url',
            field=models.URLField(default='http://172.16.254.77:8000', help_text='URL base do sistema usada para gerar links em e-mails (ex: https://meusistema.com.br)', verbose_name='URL do Sistema'),
        ),
    ]
