# Generated by Django 6.0.1 on 2026-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaogeral_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='empresa_cnpj',
            field=models.CharField(blank=True, help_text='Aparecerá no cabeçalho do orçamento', max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='empresa_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='empresa_endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='empresa_nome',
            field=models.CharField(default='Minha Empresa de TI', max_length=200, verbose_name='Nome da Sua Empresa'),
        ),
        migrations.AddField(
            model_name='configuracaogeral',
            name='empresa_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='site_url',
            field=models.URLField(default='http://localhost:8000', help_text='URL base do sistema usada para gerar links em e-mails', verbose_name='URL do Sistema'),
        ),
    ]
