# Generated by Django 6.0.1 on 2026-03-23 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra (R$)')),
                ('link_produto', models.URLField(blank=True, help_text='Link do fornecedor (Opcional)', verbose_name='Link do Produto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Nº Orçamento')),
                ('cliente_avulso_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do Cliente (Avulso)')),
                ('cliente_avulso_contato', models.CharField(blank=True, max_length=200, verbose_name='Contato (E-mail/Telefone)')),
                ('validade', models.DateField(verbose_name='Validade do Orçamento')),
                ('status', models.CharField(choices=[('NAO_ENVIADO', 'Não Enviado'), ('EM_ANALISE', 'Em Análise (Enviado)'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='NAO_ENVIADO', max_length=20, verbose_name='Status')),
                ('descricao_geral', models.TextField(help_text='Explique o escopo do projeto ou manutenção.', verbose_name='Descrição Geral do Serviço')),
                ('total_mao_de_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Mão de Obra (R$)')),
                ('total_insumos', models.DecimalField(decimal_places=2, default=0.0, help_text='Gastos com deslocamento, pedágio, alimentação, etc.', max_digits=10, verbose_name='Total Insumos/Gastos (R$)')),
                ('total_produtos_compra', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total_produtos_venda', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('valor_total_orcamento', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('lucro_equipamentos', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('lucro_total_bruto', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('lucro_total_liquido', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Selecione caso seja um cliente cadastrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemProdutoOrcamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('porcentagem_markup', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem de lucro sobre o valor de compra.', max_digits=5, verbose_name='Markup (%)')),
                ('valor_unitario_compra_registrado', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('valor_unitario_venda', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamentos.produto')),
            ],
        ),
    ]
