# Generated by Django 6.0.1 on 2026-03-26 01:18

from django.db import migrations, models

import random
import string

def gerar_hashes_para_orcamentos_existentes(apps, schema_editor):
    # Pegamos o modelo histórico de forma segura
    Orcamento = apps.get_model('orcamentos', 'Orcamento')

    for orcamento in Orcamento.objects.all():
        if not orcamento.hash_acesso:
            # Gera uma hash de 6 caracteres
            nova_hash = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
            orcamento.hash_acesso = nova_hash
            orcamento.save(update_fields=['hash_acesso'])



class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='hash_acesso',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, verbose_name='Código de Acesso'),
        ),
    ]

operations = [
        migrations.RunPython(gerar_hashes_para_orcamentos_existentes),
    ]