# Generated by Django 6.0.1 on 2026-03-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='hash_acesso',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, verbose_name='Código de Acesso'),
        ),
    ]
