# Generated by Django 6.0.1 on 2026-03-26 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_orcamento_hash_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='hash_acesso',
            field=models.CharField(blank=True, default=django.utils.timezone.now, editable=False, max_length=6, unique=True, verbose_name='Código de Acesso'),
            preserve_default=False,
        ),
    ]
